### ISSUE TITLE
Issues working but comments not working for a GHE repo

### ISSUE THREAD

**Issue by andersone1** [metrumresearchgroup/ghpm#16]
This may not be a problem and or not implemented yet, but for some reason:

### This works:

- `get_issues(org = "mrg", repo =  "Metrum-JET", .api_url = "https://ghe.metrumrg.com/api/graphql")`

### But this does not:

- `get_issue_comments(org = "mrg", repo =  "Metrum-JET", .api_url = "https://ghe.metrumrg.com/api/graphql")`

```
Error in vec_rbind(old, new) : 
  Internal error in vec_proxy_assign_opts(): proxy of type character incompatible with value proxy of type NULL.
```

This is on GHE - [this repository](https://ghe.metrumrg.com/mrg/Metrum-JET) does have comments under some of the issues.

**Comment by Blackglade** [comment]
Ahh okay, this happens on a users account that has been deleted (and becomes a ghost account). Fix is fairly straightforward. Thanks for filing the issue eric!
